name: Scheduled Backend Ping

on:
  schedule:
    - cron: '*/14 * * * *'  # cada 10 minutos
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend de Render
        run: curl -s -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" https://screenmatch-backend.onrender.com/series/inicio > /dev/null
